-- CDC Statistics Warehouse
-- Statements to create tables and views used by the CDCCollectStats utility

SET SCHEMA CDCSTATS;
CREATE TABLE CDC_STATS_ALL (
	SOURCE_DATASTORE VARCHAR(30) NOT NULL, 
	SUBSCRIPTION VARCHAR(30) NOT NULL, 
	COLLECT_TS TIMESTAMP NOT NULL,
	SOURCE_TARGET CHAR(1) NOT NULL,
	METRIC_ID INTEGER NOT NULL,
	METRIC_VALUE BIGINT,
	CONSTRAINT CDC_STATS_ALL_PK PRIMARY KEY(SOURCE_DATASTORE,SUBSCRIPTION,COLLECT_TS,SOURCE_TARGET,METRIC_ID))
	COMPRESS YES;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_DATASTORE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 1001, METRIC_VALUE)) AS SOURCE_DS_TIME_CHECK_MISSED,
		MAX(DECODE(METRIC_ID, 1002, METRIC_VALUE)) AS SOURCE_DS_FREE_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1003, METRIC_VALUE)) AS SOURCE_DS_MAX_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1004, METRIC_VALUE)) AS SOURCE_DS_TOTAL_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1005, METRIC_VALUE)) AS SOURCE_DS_GARBAGE_COLLECTION_COUNT,
		MAX(DECODE(METRIC_ID, 1006, METRIC_VALUE)) AS SOURCE_DS_GARBAGE_COLLECTION_CPU_MS,
		MAX(DECODE(METRIC_ID, 1007, METRIC_VALUE)) AS SOURCE_DS_GLOBAL_MEM_MANAGER_BYTES,
		MAX(DECODE(METRIC_ID, 2401, METRIC_VALUE)) AS SOURCE_DS_NETWORK_ERRORS
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_DB_WORKLOAD AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 1103, METRIC_VALUE)) AS SOURCE_DB_TOTAL_TRANSACTIONS,
		MAX(DECODE(METRIC_ID, 1301, METRIC_VALUE)) AS SOURCE_DB_IN_SCOPE_TRANSACTIONS,
		MAX(DECODE(METRIC_ID, 1310, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_0X_TO_1_2X,
		MAX(DECODE(METRIC_ID, 1311, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_1_2X_TO_X,
		MAX(DECODE(METRIC_ID, 1312, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_X_TO_2X,
		MAX(DECODE(METRIC_ID, 1313, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_2X_TO_4X,
		MAX(DECODE(METRIC_ID, 1314, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_4X_TO_8X,
		MAX(DECODE(METRIC_ID, 1315, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_8X_AND_LARGER
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_READER_PARSER AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 101, METRIC_VALUE)) AS SOURCE_READER_DB_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 1101, METRIC_VALUE)) AS SOURCE_READER_PHYSICAL_BYTES_READ,
		MAX(DECODE(METRIC_ID, 1104, METRIC_VALUE)) AS SOURCE_READER_THREAD_CPU_MS_PER_S,
		MAX(DECODE(METRIC_ID, 1201, METRIC_VALUE)) AS SOURCE_PARSER_DISK_WRITES_BYTES,
		MAX(DECODE(METRIC_ID, 1202, METRIC_VALUE)) AS SOURCE_PARSER_DISK_READS_BYTES,
		MAX(DECODE(METRIC_ID, 1203, METRIC_VALUE)) AS SOURCE_PARSER_DISK_SIZE_BYTES,
		MAX(DECODE(METRIC_ID, 1304, METRIC_VALUE)) AS SOURCE_PARSER_DDL_OPERATIONS,
		MAX(DECODE(METRIC_ID, 1401, METRIC_VALUE)) AS SOURCE_SCRAPE_DISK_WRITES_BYTES,
		MAX(DECODE(METRIC_ID, 1402, METRIC_VALUE)) AS SOURCE_SCRAPE_DISK_READ_BYTES,
		MAX(DECODE(METRIC_ID, 1403, METRIC_VALUE)) AS SOURCE_SCRAPE_DISK_SIZE_BYTES
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_ENGINE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 102, METRIC_VALUE)) AS SOURCE_ENGINE_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 104, METRIC_VALUE)) AS SOURCE_ENGINE_PRE_FILTER_INSERTS,
		MAX(DECODE(METRIC_ID, 105, METRIC_VALUE)) AS SOURCE_ENGINE_PRE_FILTER_UPDATES,
		MAX(DECODE(METRIC_ID, 106, METRIC_VALUE)) AS SOURCE_ENGINE_PRE_FILTER_DELETES,
		MAX(DECODE(METRIC_ID, 107, METRIC_VALUE)) AS SOURCE_ENGINE_POST_FILTER_INSERTS,
		MAX(DECODE(METRIC_ID, 108, METRIC_VALUE)) AS SOURCE_ENGINE_POST_FILTER_UPDATES,
		MAX(DECODE(METRIC_ID, 109, METRIC_VALUE)) AS SOURCE_ENGINE_POST_FILTER_DELETES,
		MAX(DECODE(METRIC_ID, 118, METRIC_VALUE)) AS SOURCE_ENGINE_LATENCY_VALUE_SECS,
		MAX(DECODE(METRIC_ID, 1501, METRIC_VALUE)) AS SOURCE_ENGINE_ROWS_DERIVED_COL,
		MAX(DECODE(METRIC_ID, 1502, METRIC_VALUE)) AS SOURCE_ENGINE_ROWS_CALLING_SOURE_DB,
		MAX(DECODE(METRIC_ID, 1503, METRIC_VALUE)) AS SOURCE_ENGINE_ROWS_CALLING_USER_EXITS,
		MAX(DECODE(METRIC_ID, 1504, METRIC_VALUE)) AS SOURCE_ENGINE_THREAD_CPU_MS_PER_S,
		MAX(DECODE(METRIC_ID, 1507, METRIC_VALUE)) AS SOURCE_ENGINE_MBCS_CONVERSIONS_BYTES
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_COMMS AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 103, METRIC_VALUE)) AS SOURCE_COMMS_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 2402, METRIC_VALUE)) AS SOURCE_COMMS_NETWORK_LATENCY_MS,
		MAX(DECODE(METRIC_ID, 2404, METRIC_VALUE)) AS SOURCE_COMMS_MISSING_ROUND_TRIP,
		MAX(DECODE(METRIC_ID, 2406, METRIC_VALUE)) AS SOURCE_COMMS_KEEP_ALIVE_SENT,
		MAX(DECODE(METRIC_ID, 2408, METRIC_VALUE)) AS SOURCE_COMMS_BYTES_SENT
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_DATASTORE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 1001, METRIC_VALUE)) AS TARGET_DS_TIME_CHECK_MISSED,
		MAX(DECODE(METRIC_ID, 1002, METRIC_VALUE)) AS TARGET_DS_FREE_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1003, METRIC_VALUE)) AS TARGET_DS_MAX_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1004, METRIC_VALUE)) AS TARGET_DS_TOTAL_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1005, METRIC_VALUE)) AS TARGET_DS_GARBAGE_COLLECTION_COUNT,
		MAX(DECODE(METRIC_ID, 1006, METRIC_VALUE)) AS TARGET_DS_GARBAGE_COLLECTION_CPU_MS,
		MAX(DECODE(METRIC_ID, 1007, METRIC_VALUE)) AS TARGET_DS_GLOBAL_MEM_MANAGER_BYTES,
		MAX(DECODE(METRIC_ID, 2401, METRIC_VALUE)) AS TARGET_DS_NETWORK_ERRORS
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_COMMS AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 201, METRIC_VALUE)) AS TARGET_COMMS_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 2403, METRIC_VALUE)) AS TARGET_COMMS_NETWORK_LATENCY_MS,
		MAX(DECODE(METRIC_ID, 2405, METRIC_VALUE)) AS TARGET_COMMS_MISSING_ROUND_TRIP_RESPONSE,
		MAX(DECODE(METRIC_ID, 2407, METRIC_VALUE)) AS TARGET_KEEP_ALIVE_RECEIVED,
		MAX(DECODE(METRIC_ID, 2409, METRIC_VALUE)) AS TARGET_BYTES_RECEIVED
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_ENGINE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 202, METRIC_VALUE)) AS TARGET_ENGINE_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 204, METRIC_VALUE)) AS TARGET_ENGINE_SOURCE_INSERTS,
		MAX(DECODE(METRIC_ID, 205, METRIC_VALUE)) AS TARGET_ENGINE_SOURCE_UPDATES,
		MAX(DECODE(METRIC_ID, 204, METRIC_VALUE)) AS TARGET_ENGINE_SOURCE_DELETES,
		MAX(DECODE(METRIC_ID, 2101, METRIC_VALUE)) AS TARGET_ENGINE_THREAD_CPU_MS_PER_S,
		MAX(DECODE(METRIC_ID, 2103, METRIC_VALUE)) AS TARGET_ENGINE_ROWS_EVALUATING_EXPRESSION,
		MAX(DECODE(METRIC_ID, 2104, METRIC_VALUE)) AS TARGET_ENGINE_ROWS_CALLING_TARGET_DB,
		MAX(DECODE(METRIC_ID, 2105, METRIC_VALUE)) AS TARGET_ENGINE_ROWS_CALLING_USER_EXITS,
		MAX(DECODE(METRIC_ID, 2106, METRIC_VALUE)) AS TARGET_ENGINE_MBCS_CONVERSIONS_BYTES,
		MAX(DECODE(METRIC_ID, 2107, METRIC_VALUE)) AS TARGET_ENGINE_NET_EFFECT_REMOVAL
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_APPLY AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 207, METRIC_VALUE)) AS TARGET_APPLY_INSERTS,
		MAX(DECODE(METRIC_ID, 208, METRIC_VALUE)) AS TARGET_APPLY_UPDATES,
		MAX(DECODE(METRIC_ID, 209, METRIC_VALUE)) AS TARGET_APPLY_DELETES,
		(MAX(DECODE(METRIC_ID, 207, METRIC_VALUE)) + MAX(DECODE(METRIC_ID, 208, METRIC_VALUE)) + MAX(DECODE(METRIC_ID, 209, METRIC_VALUE))) AS TARGET_APPLY_TOTAL_OPS,
		MAX(DECODE(METRIC_ID, 216, METRIC_VALUE)) AS TARGET_APPLY_LATENCY_S,
		MAX(DECODE(METRIC_ID, 2301, METRIC_VALUE)) AS TARGET_APPLY_THREAD_CPU_MS_PER_S,
		MAX(DECODE(METRIC_ID, 2303, METRIC_VALUE)) AS TARGET_APPLY_CDR_CONFLICTS,
		MAX(DECODE(METRIC_ID, 2304, METRIC_VALUE)) AS TARGET_APPLY_ADAPTIVE_APPLY_CHANGES,
		MAX(DECODE(METRIC_ID, 2305, METRIC_VALUE)) AS TARGET_APPLY_APPLY_COMMITS,
		MAX(DECODE(METRIC_ID, 2306, METRIC_VALUE)) AS TARGET_APPLY_AVERAGE_ARRAY_SIZE,
		MAX(DECODE(METRIC_ID, 2307, METRIC_VALUE)) AS TARGET_APPLY_DATA_ERRORS_IGNORED,
		MAX(DECODE(METRIC_ID, 2308, METRIC_VALUE)) AS TARGET_APPLY_SLOW_DB_OPERATIONS,
		MAX(DECODE(METRIC_ID, 1706, METRIC_VALUE)) AS TARGET_APPLY_HTTP_POST_COUNT,
		MAX(DECODE(METRIC_ID, 1710, METRIC_VALUE)) AS TARGET_APPLY_HTTP_POST_SIZE_0_10_COUNT,
		MAX(DECODE(METRIC_ID, 1711, METRIC_VALUE)) AS TARGET_APPLY_HTTP_POST_SIZE_11_100_COUNT,
		MAX(DECODE(METRIC_ID, 1712, METRIC_VALUE)) AS TARGET_APPLY_HTTP_POST_SIZE_101_1000_COUNT,
		MAX(DECODE(METRIC_ID, 1713, METRIC_VALUE)) AS TARGET_APPLY_HTTP_POST_SIZE_1001_HIGH_COUNT,
		MAX(DECODE(METRIC_ID, 2108, METRIC_VALUE)) AS TARGET_APPLY_RETRY_ATTEMPT_COUNT
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_APPLY_THROUGPUT
AS WITH DELTAS AS 
(SELECT
   ROW_NUMBER() OVER (PARTITION BY SOURCE_DATASTORE, SUBSCRIPTION ORDER BY COLLECT_TS) row,
   SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS, TARGET_APPLY_INSERTS, TARGET_APPLY_UPDATES, TARGET_APPLY_DELETES, TARGET_APPLY_TOTAL_OPS
 FROM CDC_STATS_TARGET_APPLY)
SELECT B.SOURCE_DATASTORE, B.SUBSCRIPTION, B.COLLECT_TS, 
  (B.COLLECT_TS-A.COLLECT_TS) TARGET_APPLY_TIME_DELTA,
  (B.TARGET_APPLY_INSERTS-A.TARGET_APPLY_INSERTS) AS TARGET_APPLY_INSERTS_DELTA,
  (B.TARGET_APPLY_UPDATES-A.TARGET_APPLY_UPDATES) AS TARGET_APPLY_UPDATES_DELTA,
  (B.TARGET_APPLY_DELETES-A.TARGET_APPLY_DELETES) AS TARGET_APPLY_DELETES_DELTA,
  (B.TARGET_APPLY_TOTAL_OPS-A.TARGET_APPLY_TOTAL_OPS) AS TARGET_APPLY_TOTAL_OPS_DELTA,
  ((B.TARGET_APPLY_INSERTS-A.TARGET_APPLY_INSERTS)/(B.COLLECT_TS-A.COLLECT_TS)) AS TARGET_APPLY_INSERTS_PER_S,
  ((B.TARGET_APPLY_UPDATES-A.TARGET_APPLY_UPDATES)/(B.COLLECT_TS-A.COLLECT_TS)) AS TARGET_APPLY_UPDATES_PER_S,
  ((B.TARGET_APPLY_DELETES-A.TARGET_APPLY_DELETES)/(B.COLLECT_TS-A.COLLECT_TS)) AS TARGET_APPLY_DELETES_PER_S,
  ((B.TARGET_APPLY_TOTAL_OPS-A.TARGET_APPLY_TOTAL_OPS)/(B.COLLECT_TS-A.COLLECT_TS)) AS TARGET_APPLY_TOTAL_OPS_PER_S
FROM DELTAS A INNER JOIN DELTAS B
ON A.SOURCE_DATASTORE=B.SOURCE_DATASTORE AND A.SUBSCRIPTION=B.SUBSCRIPTION AND B.ROW=A.ROW+1
WHERE ((B.TARGET_APPLY_INSERTS-A.TARGET_APPLY_INSERTS)/(B.COLLECT_TS-A.COLLECT_TS)) >=0 AND
      ((B.TARGET_APPLY_UPDATES-A.TARGET_APPLY_UPDATES)/(B.COLLECT_TS-A.COLLECT_TS)) >= 0 AND
      ((B.TARGET_APPLY_DELETES-A.TARGET_APPLY_DELETES)/(B.COLLECT_TS-A.COLLECT_TS)) >= 0;
	
CREATE TABLE CDC_SUB_STATUS (
	SOURCE_DATASTORE VARCHAR(30) NOT NULL, 
	SUBSCRIPTION VARCHAR(30) NOT NULL, 
	COLLECT_TS TIMESTAMP NOT NULL,
	SUBSCRIPTION_STATUS VARCHAR(30),
	CONSTRAINT CDC_SUB_STATUS PRIMARY KEY(SOURCE_DATASTORE,SUBSCRIPTION,COLLECT_TS))
	COMPRESS YES;
	
	