-- CDC Statistics Warehouse
-- Statements to create tables and views used by the CDCCollectStats utility

SET SCHEMA CDCSTATS;
CREATE TABLE CDC_STATS_ALL (
	SOURCE_DATASTORE VARCHAR(30) NOT NULL, 
	SUBSCRIPTION VARCHAR(30) NOT NULL, 
	COLLECT_TS TIMESTAMP NOT NULL,
	SOURCE_TARGET CHAR(1) NOT NULL,
	METRIC_ID INTEGER NOT NULL,
	METRIC_VALUE BIGINT,
	CONSTRAINT CDC_STATS_ALL_PK PRIMARY KEY(SOURCE_DATASTORE,SUBSCRIPTION,COLLECT_TS,SOURCE_TARGET,METRIC_ID))
	COMPRESS YES;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_DATASTORE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 1001, METRIC_VALUE)) AS SOURCE_DS_TIME_CHECK_MISSED,
		MAX(DECODE(METRIC_ID, 1002, METRIC_VALUE)) AS SOURCE_DS_FREE_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1003, METRIC_VALUE)) AS SOURCE_DS_MAX_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1004, METRIC_VALUE)) AS SOURCE_DS_TOTAL_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1005, METRIC_VALUE)) AS SOURCE_DS_GARBAGE_COLLECTION_COUNT,
		MAX(DECODE(METRIC_ID, 1006, METRIC_VALUE)) AS SOURCE_DS_GARBAGE_COLLECTION_CPU_MS,
		MAX(DECODE(METRIC_ID, 1007, METRIC_VALUE)) AS SOURCE_DS_GLOBAL_MEM_MANAGER_BYTES,
		MAX(DECODE(METRIC_ID, 2401, METRIC_VALUE)) AS SOURCE_DS_NETWORK_ERRORS
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_DB_WORKLOAD AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 1103, METRIC_VALUE)) AS SOURCE_DB_TOTAL_TRANSACTIONS,
		MAX(DECODE(METRIC_ID, 1301, METRIC_VALUE)) AS SOURCE_DB_IN_SCOPE_TRANSACTIONS,
		MAX(DECODE(METRIC_ID, 1310, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_0X_TO_1_2X,
		MAX(DECODE(METRIC_ID, 1311, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_1_2X_TO_X,
		MAX(DECODE(METRIC_ID, 1312, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_X_TO_2X,
		MAX(DECODE(METRIC_ID, 1313, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_2X_TO_4X,
		MAX(DECODE(METRIC_ID, 1314, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_4X_TO_8X,
		MAX(DECODE(METRIC_ID, 1315, METRIC_VALUE)) AS SOURCE_DB_TX_HIST_8X_AND_LARGER
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_SOURCE_READER_PARSER AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 101, METRIC_VALUE)) AS SOURCE_READER_DB_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 1101, METRIC_VALUE)) AS SOURCE_READER_PHYSICAL_BYTES_READ,
		MAX(DECODE(METRIC_ID, 1104, METRIC_VALUE)) AS SOURCE_READER_THREAD_CPU_MS_PER_S,
		MAX(DECODE(METRIC_ID, 1201, METRIC_VALUE)) AS SOURCE_PARSER_DISK_WRITES_BYTES,
		MAX(DECODE(METRIC_ID, 1202, METRIC_VALUE)) AS SOURCE_PARSER_DISK_READS_BYTES,
		MAX(DECODE(METRIC_ID, 1203, METRIC_VALUE)) AS SOURCE_PARSER_DISK_SIZE_BYTES,
		MAX(DECODE(METRIC_ID, 1304, METRIC_VALUE)) AS SOURCE_PARSER_DDL_OPERATIONS
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='S'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_DATASTORE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 1001, METRIC_VALUE)) AS TARGET_DS_TIME_CHECK_MISSED,
		MAX(DECODE(METRIC_ID, 1002, METRIC_VALUE)) AS TARGET_DS_FREE_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1003, METRIC_VALUE)) AS TARGET_DS_MAX_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1004, METRIC_VALUE)) AS TARGET_DS_TOTAL_MEMORY_BYTES,
		MAX(DECODE(METRIC_ID, 1005, METRIC_VALUE)) AS TARGET_DS_GARBAGE_COLLECTION_COUNT,
		MAX(DECODE(METRIC_ID, 1006, METRIC_VALUE)) AS TARGET_DS_GARBAGE_COLLECTION_CPU_MS,
		MAX(DECODE(METRIC_ID, 1007, METRIC_VALUE)) AS TARGET_DS_GLOBAL_MEM_MANAGER_BYTES,
		MAX(DECODE(METRIC_ID, 2401, METRIC_VALUE)) AS TARGET_DS_NETWORK_ERRORS
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_COMMS AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 201, METRIC_VALUE)) AS TARGET_COMMS_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 2403, METRIC_VALUE)) AS TARGET_COMMS_NETWORK_LATENCY_MS,
		MAX(DECODE(METRIC_ID, 2405, METRIC_VALUE)) AS TARGET_COMMS_MISSING_ROUND_TRIP_RESPONSE,
		MAX(DECODE(METRIC_ID, 2407, METRIC_VALUE)) AS TARGET_KEEP_ALIVE_RECEIVED,
		MAX(DECODE(METRIC_ID, 2409, METRIC_VALUE)) AS TARGET_BYTES_RECEIVED
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;
	
CREATE OR REPLACE VIEW CDC_STATS_TARGET_ENGINE AS
	SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS,
		MAX(DECODE(METRIC_ID, 202, METRIC_VALUE)) AS TARGET_ENGINE_BYTES_PROCESSED,
		MAX(DECODE(METRIC_ID, 204, METRIC_VALUE)) AS TARGET_ENGINE_SOURCE_INSERTS,
		MAX(DECODE(METRIC_ID, 205, METRIC_VALUE)) AS TARGET_ENGINE_SOURCE_UPDATES,
		MAX(DECODE(METRIC_ID, 204, METRIC_VALUE)) AS TARGET_ENGINE_SOURCE_DELETES,
		MAX(DECODE(METRIC_ID, 2101, METRIC_VALUE)) AS TARGET_ENGINE_THREAD_CPU_MS_PER_S,
		MAX(DECODE(METRIC_ID, 2103, METRIC_VALUE)) AS TARGET_ENGINE_ROWS_EVALUATING_EXPRESSION,
		MAX(DECODE(METRIC_ID, 2104, METRIC_VALUE)) AS TARGET_ENGINE_ROWS_CALLING_TARGET_DB,
		MAX(DECODE(METRIC_ID, 2105, METRIC_VALUE)) AS TARGET_ENGINE_ROWS_CALLING_USER_EXITS,
		MAX(DECODE(METRIC_ID, 2106, METRIC_VALUE)) AS TARGET_ENGINE_MBCS_CONVERSIONS_BYTES
	FROM CDC_STATS_ALL
		WHERE SOURCE_TARGET='T'
	GROUP BY SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS;

	
SELECT SOURCE_DATASTORE, SUBSCRIPTION, COLLECT_TS, SOURCE_TARGET, 
	MAX(DECODE(METRIC_ID, 204, METRIC_VALUE)) AS APPLY_INSERTS,
	MAX(DECODE(METRIC_ID, 205, METRIC_VALUE)) AS APPLY_UPDATES,
	MAX(DECODE(METRIC_ID, 204, METRIC_VALUE)) AS APPLY_DELETES
FROM CDC_STATS_ALL
GROUP BY SOURCE_DATASTORE, SUBSCRIPTINO, COLLECT_TS, SOURCE_TARGET;
	
CREATE TABLE CDC_SUB_STATUS (
	SOURCE_DATASTORE VARCHAR(30) NOT NULL, 
	SUBSCRIPTION VARCHAR(30) NOT NULL, 
	COLLECT_TS TIMESTAMP NOT NULL,
	SUBSCRIPTION_STATUS VARCHAR(30),
	CONSTRAINT CDC_SUB_STATUS PRIMARY KEY(SOURCE_DATASTORE,SUBSCRIPTION,COLLECT_TS))
	COMPRESS YES;
	
	