-- CDC Statistics Warehouse
-- Statements to create tables and views used by the CDCCollectStats utility

SET SCHEMA CDCSTATS;
CREATE TABLE CDC_STATS_ALL (
	SOURCE_DATASTORE VARCHAR(30) NOT NULL, 
	SUBSCRIPTION VARCHAR(30) NOT NULL, 
	COLLECT_TS TIMESTAMP NOT NULL,
	SOURCE_TARGET CHAR(1) NOT NULL,
	METRIC_ID INTEGER NOT NULL,
	METRIC_VALUE BIGINT,
	CONSTRAINT CDC_STATS_ALL_PK PRIMARY KEY(SOURCE_DATASTORE,SUBSCRIPTION,COLLECT_TS,SOURCE_TARGET,METRIC_ID))
	COMPRESS YES;
	
CREATE TABLE CDC_SUB_STATUS (
	SOURCE_DATASTORE VARCHAR(30) NOT NULL, 
	SUBSCRIPTION VARCHAR(30) NOT NULL, 
	COLLECT_TS TIMESTAMP NOT NULL,
	SUBSCRIPTION_STATUS VARCHAR(30),
	CONSTRAINT CDC_SUB_STATUS PRIMARY KEY(SOURCE_DATASTORE,SUBSCRIPTION,COLLECT_TS))
	COMPRESS YES;
	
	